_keys:
- key_id: arn:aws:kms:us-east-1:477593580061:alias/biscuit-default
  key_manager: kms
  algorithm: secretbox
- key_id: arn:aws:kms:us-west-1:477593580061:alias/biscuit-default
  key_manager: kms
  algorithm: secretbox
- key_id: arn:aws:kms:us-west-2:477593580061:alias/biscuit-default
  key_manager: kms
  algorithm: secretbox
test::lob-api-key:
- key_id: arn:aws:kms:us-west-1:477593580061:key/c9e8618c-1fee-4400-a7d0-0914d433f25e
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjOcf0L8wNJeJByFP9BGFtLH/4xBpSevkIQANEiasdfFwAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDL0rYMFU7b+uQDeWNgIBEIA7JnOaXrE7DuoDqn8cCHcs5bHJIWbUFFA4v7wf+hz+dBCOR9oE9wvN60BzS4PBzn7h5oOJ1qyfSgUc1UE=
  ciphertext: qVlBdoGsS3c13XbDYGF/AhAkktgTAC1bttmV0PAsO/+IIR3+evb36xuawNX9VWf8ZeBlwpZTxkhwVvafX2ZcGs+PEnZumdMJ6lnBdoxQksA=
- key_id: arn:aws:kms:us-west-2:477593580061:key/e5ebd4c6-e24a-4159-8eee-936148bb73bf
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHj6hSFXIChokq2jG90/VQtkQWJULdzekrDyuaPdAwNk4wAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDGnXDpiZ7LnQS9GKeAIBEIA7JxaXqV/76cBiZy+QXemsMFIIGS0AhGmM9jNUQ5K2t0F9n64fUmKY1cRJLFCTORB0sCzXoLXdSd3u/Ho=
  ciphertext: VVb8azdveIldqGo/Azx6cFz+XiubBNm75WG3qdKEnYLj6jDz6wF7rCux/gYHQ7pSxu8N4QiRPqc3Z4f0gHu/NP3tPSR5KG8veRMT00+Dy+M=
- key_id: arn:aws:kms:us-east-1:477593580061:key/5abf5adc-e0b7-4df5-bb5e-a42f7b6f4888
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjGKDJeTvC9Smjh5kvaPCZhKrQzkdNH/X2lzLUr9dRntAAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDAlvHCbxdFJpykwqgQIBEIA7RATlGNm4xTl3+l6Xp/2qncUXMMHA2RHb67Ey7bNp29ahd3WnWpSgykDnFKWw414RyumAYHILo3Gl0VQ=
  ciphertext: VKrC4q0nsk+kUOCZ+B4TOBAEULKx6uGjFFrcR55oXkoUkQCxiUGnyTgtAd1BqYO712WFG63WbwwH3GNahulnXn+D3hzpDFWV2UXkLztN+Xs=
