_keys:
- key_id: arn:aws:kms:us-east-1:477593580061:alias/biscuit-default
  key_manager: kms
  algorithm: secretbox
- key_id: arn:aws:kms:us-west-1:477593580061:alias/biscuit-default
  key_manager: kms
  algorithm: secretbox
- key_id: arn:aws:kms:us-west-2:477593580061:alias/biscuit-default
  key_manager: kms
  algorithm: secretbox
boxfuse-secret:
- key_id: arn:aws:kms:us-west-1:477593580061:key/c9e8618c-1fee-4400-a7d0-0914d433f25e
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjOcf0L8wNJeJByFP9BGFtLH/4xBpSevkIQANEiasdfFwAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDOXDoHkdjSht3fZoVQIBEIA7H+AfozdCyvEdcv1LNIQ3IY1EzlG8wHn+eeyjk/soLvHFknSTvRJ+CkMwpY/W21LrLDl2Tpbrpvq4z6E=
  ciphertext: 7EfwIzzppVUx1HkGPmhricoXjWR4aYmilZdCeSCEjV2Si1Ou3qB/aiebvL+yYxy+TZXRa0BlxT13N20LHJlc4m9Ok9g0ophxvKZnA/N7YziMQ/l/Ask5vCKJI0lQ/p7NQMIqeoZ/M+M=
- key_id: arn:aws:kms:us-west-2:477593580061:key/e5ebd4c6-e24a-4159-8eee-936148bb73bf
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHj6hSFXIChokq2jG90/VQtkQWJULdzekrDyuaPdAwNk4wAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDFY1ZD4YKwtDKQHZWAIBEIA74U4Hv6ztFpVVAU9p+s/JF5ZCNo5QMpKZK6eGtLw/U9KhTMQ00ZcaO6fRb9jdNLIhS0bYF1intJ7mYvw=
  ciphertext: JP7GFNP1wyA9BTMT66RONSByPrOWkgf08a0p5OLxLnjqao2mfow7gI7Lja1KcPcYMN6KiQwywZGaMKwnj5px0KuK9Dd25kI9JiinspqRLEpSkT7LIR5m57moH+6zRz1WBLyvcdroCys=
- key_id: arn:aws:kms:us-east-1:477593580061:key/5abf5adc-e0b7-4df5-bb5e-a42f7b6f4888
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjGKDJeTvC9Smjh5kvaPCZhKrQzkdNH/X2lzLUr9dRntAAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDPo1sMt/5dPX3C+/EgIBEIA7fXtYapMrIiPrbS920BXr76LWnaTVnZU/AGr0/2rc7hU0GcZ1FRM7qZuliMStEisVGTZ9AFHTkNCsJc8=
  ciphertext: EQOSq53HC8fsOwRsuRECNW9a2CQFF/JIm1S2BpwAIbBtW0FC7mwZ24qGRk6Mqx8rtoUFdWzuGr76Ei7Uba3yKzBFmTJHBXPZr2Yoy18BieMSMnGHDPmgVkoS31XLly8i28e1F6K0H4I=
boxfuse-user:
- key_id: arn:aws:kms:us-west-1:477593580061:key/c9e8618c-1fee-4400-a7d0-0914d433f25e
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjOcf0L8wNJeJByFP9BGFtLH/4xBpSevkIQANEiasdfFwAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDC6ZpTUiuYY8kvDe4wIBEIA7+7xkwxGMWtgpZ6RbkQYB9iHmX0oMuQAqw2ziu46a/9ZoY9mprA8wjK3bFGYBvj3B2/+DoDBB/U95lqw=
  ciphertext: 9o3zHPujWZbcJT7aGsGs8ZyXonRwhnnK762NU4x6gWy8gAmKxC7V8nJJKEzK/0WPv8gdA08LXA47HXacFuOvsa2lYCrqOu1I
- key_id: arn:aws:kms:us-west-2:477593580061:key/e5ebd4c6-e24a-4159-8eee-936148bb73bf
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHj6hSFXIChokq2jG90/VQtkQWJULdzekrDyuaPdAwNk4wAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDDZOVLPlJQt20VSbrgIBEIA7wAox9HIL0vjBD1hU821hVV5Xi9Mv0UNh/dmlgQzmXlQphEuDH1kzPhul3bCEeRo4/IQXMQnBUW2Ruok=
  ciphertext: LN301vw8P0XEXWDw1s8baXF57kUHAC7iUidY7DEx7cMqcC+biMizH+N4nPlLRXVgIDUEefjEFmvpSC5HoeY9v4v+Xs9NjsqQ
- key_id: arn:aws:kms:us-east-1:477593580061:key/5abf5adc-e0b7-4df5-bb5e-a42f7b6f4888
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjGKDJeTvC9Smjh5kvaPCZhKrQzkdNH/X2lzLUr9dRntAAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDExP/Sq2J3WjBdJ51AIBEIA71iTaPxe4AiT+QXQODxGNWCpapPifVbNGYoHuijRBGW8/3CJWekoyOLHJ2xyMoiAggLjsaJZrFBmX5SI=
  ciphertext: c9P12acbM1qe0g94d06wg/2JviMsXPKH1t+yc3jxf2i1GDNMkAXd0lXeJMr+/xKtzdCN2Ep8sxOKqFrBMn5Sa+qYU00woOrN
id-sandbox-password:
- key_id: arn:aws:kms:us-east-1:477593580061:key/5abf5adc-e0b7-4df5-bb5e-a42f7b6f4888
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjGKDJeTvC9Smjh5kvaPCZhKrQzkdNH/X2lzLUr9dRntAAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDBdaRJ00TryIbefL7QIBEIA7PJZYPsJMEpSZknHk8wkYXhCEa+Wr0Gp8+VjPCrRG/a/mFSJtOi0Q8A7Mtprcwt980pKom704OdewR1Y=
  ciphertext: qLplesPZnKPGsif2kfye0Y6gf20rXg8xTPhsBNySZtoTt2RuS1XwSUwDzK6djACH5EDd6Q==
- key_id: arn:aws:kms:us-west-1:477593580061:key/c9e8618c-1fee-4400-a7d0-0914d433f25e
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjOcf0L8wNJeJByFP9BGFtLH/4xBpSevkIQANEiasdfFwAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDBRywb7aVY5TWCQbwwIBEIA7FlNfgO7IySdeHy638b3SmeMl04dJtaDDMjqrT7J+RkYd6SHKkbkStQno6phouA5pOObR9EccDfl4PB4=
  ciphertext: L6F7mz78M7bEQ8WqcvOu4Ul1Sbx3BP3UWxhUjck62tqp/5UKP7mwmj9frL7h/CeTon6ASg==
- key_id: arn:aws:kms:us-west-2:477593580061:key/e5ebd4c6-e24a-4159-8eee-936148bb73bf
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHj6hSFXIChokq2jG90/VQtkQWJULdzekrDyuaPdAwNk4wAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDMicrkDsW8GvcoWPzQIBEIA7sQMc74SEjl/n9JplLj1Jq5kadF8DlXRfZaRS/xfQ9cBLgTSBebi18jsoj3ewRe6/XhTxvS/merM3tsg=
  ciphertext: IC/ESs4oWUxiO9N0nJLezHlh9xru2pdWqLv/rhdLibWf/q6TD0iI8fpGi6OHPQDr8caaGw==
