_keys:
- key_id: arn:aws:kms:us-east-1:477593580061:alias/biscuit-default
  key_manager: kms
  algorithm: secretbox
- key_id: arn:aws:kms:us-west-1:477593580061:alias/biscuit-default
  key_manager: kms
  algorithm: secretbox
- key_id: arn:aws:kms:us-west-2:477593580061:alias/biscuit-default
  key_manager: kms
  algorithm: secretbox
