_keys:
- key_id: arn:aws:kms:us-east-1:477593580061:alias/biscuit-default
  key_manager: kms
  algorithm: secretbox
- key_id: arn:aws:kms:us-west-1:477593580061:alias/biscuit-default
  key_manager: kms
  algorithm: secretbox
- key_id: arn:aws:kms:us-west-2:477593580061:alias/biscuit-default
  key_manager: kms
  algorithm: secretbox
local::id-me-client-id:
- key_id: arn:aws:kms:us-west-1:477593580061:key/c9e8618c-1fee-4400-a7d0-0914d433f25e
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjOcf0L8wNJeJByFP9BGFtLH/4xBpSevkIQANEiasdfFwAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDCX+Kh54mXsUXxx/swIBEIA7AQ+01WNfzHoe++WgKM3sxdq87H5xJx8pS3/X84QinDWcGMEANbMf0lfPPFLIe66pwBCB5uYuPc+rPf4=
  ciphertext: 53FmuAQ3VaMsObnKl/C19Jx1dXXVczkShlaqWThk6sD8cQtQcGIJHEa1llUOS2luQJ6wZJ68Hu+pBTZLEK4fCbpaco4hTZ3a
- key_id: arn:aws:kms:us-west-2:477593580061:key/e5ebd4c6-e24a-4159-8eee-936148bb73bf
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHj6hSFXIChokq2jG90/VQtkQWJULdzekrDyuaPdAwNk4wAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDA6076dEWZTCL4NZaQIBEIA7hkm1PU6UVoEpk9RnExpFg5lzRFnbXZZjfPiMVMcqNEROdYEfblAHZxmziP5hzlovGq2UTCewjKu0wcc=
  ciphertext: 8X16d90o3UOobG9FwiSvYh+gbaTH7R35tN7yF0wn0dzSVWcKkF6hyCRNzch6cLD+c2zac7cv1Gg/qOGUuEg4GxdTJgGvxQv+
- key_id: arn:aws:kms:us-east-1:477593580061:key/5abf5adc-e0b7-4df5-bb5e-a42f7b6f4888
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjGKDJeTvC9Smjh5kvaPCZhKrQzkdNH/X2lzLUr9dRntAAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDD5nNVHemW8je7QJHwIBEIA7uZ/gVqJkY+iqmbjVereIbP6ggGIbLzTwzWznkKsG/KEEVSN3/ELWdNOVQAQOjqXJiOkwB0Ykglp1FxE=
  ciphertext: UZqTLFTaxsekRMgFGRH6owmcncZxJ893+/Eml9o3nY5yhU/6lTRokfyt5wxXMZ+euBCOjSNlJA4T+6d4s+ICceKeznInoCpc
local::id-me-client-secret:
- key_id: arn:aws:kms:us-west-1:477593580061:key/c9e8618c-1fee-4400-a7d0-0914d433f25e
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjOcf0L8wNJeJByFP9BGFtLH/4xBpSevkIQANEiasdfFwAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDKcnCsUhgCL0U5quEAIBEIA7o1Lsn2ltgL8vNXaCaVdDsmdy+kBMUB/rhqtK1EAF0uVevoUfsS9U7Bf3w+Q8oomFQcqLNfpA29zpq6E=
  ciphertext: Ie6iDE+lO4/8pIIAIqctyR2hgDzxSYIJa6qO+vAxsi6yX/QIcrEW7faai4wHgvXaH4JZhZBwzdwLBMoI8jPXvQVGuMmg9fsA
- key_id: arn:aws:kms:us-west-2:477593580061:key/e5ebd4c6-e24a-4159-8eee-936148bb73bf
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHj6hSFXIChokq2jG90/VQtkQWJULdzekrDyuaPdAwNk4wAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDLKRPE0vTu/xSOdMVQIBEIA7/v0L53a6eoP7MEmGeEVYNFQBjYPr6AcfeVU+q/hMmOBZr4ZWKSKY1Y0dBo/P7Ll8wYdFfuGZ4wpm604=
  ciphertext: pPnGHqUVqQg1nDjsTlZ/+OYig6GZKPOY5ehhLLw5m4+08gXKVZnhGnzc9NFlvQFWRpeALXRbPr8uq/wONyEuxW2KzwtIl1Be
- key_id: arn:aws:kms:us-east-1:477593580061:key/5abf5adc-e0b7-4df5-bb5e-a42f7b6f4888
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjGKDJeTvC9Smjh5kvaPCZhKrQzkdNH/X2lzLUr9dRntAAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDEA9b5Up0X61faeB7gIBEIA7GJOnJ/CNHhUpXgqlE+du5RinLwm+9XskbxbEASZAu/oFRmF0dW5CwtQxVoem0IOkj9d48lvt1Lk9fU8=
  ciphertext: 360gSuF9NOWnsnSvwNXlqOrMwrtB7BXkHtsDnkbX9IIW1q79VmlQBqstLjjgD+5Q6p3ldlmkmrlJj4lGEeaQjuyrzNVGAzCJ
local::lob-api-key:
- key_id: arn:aws:kms:us-west-2:477593580061:key/e5ebd4c6-e24a-4159-8eee-936148bb73bf
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHj6hSFXIChokq2jG90/VQtkQWJULdzekrDyuaPdAwNk4wAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDPYZ+BwN9NPrsaDX/gIBEIA7du9ALVuUX72mXfLS26/jLbk2XL0NaFHanGE0a2DwWe4SS0P5FfWpDUL0dhY0mCKg86OUQAlIyPqDw3g=
  ciphertext: npYoc/EYixGJegXMMvp1yK9esraMa54N4N/2ZSfqYr56FbQjRBEymtSLLbkXLGxDa5xqVJ5Vvd/bsah6VWN9SUm6XRPOYnVde2qMlODgXTc=
- key_id: arn:aws:kms:us-west-1:477593580061:key/c9e8618c-1fee-4400-a7d0-0914d433f25e
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjOcf0L8wNJeJByFP9BGFtLH/4xBpSevkIQANEiasdfFwAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDOht5941ugcDyYx29QIBEIA7FyANKkcDs8imfCZuB9dIMe6JM/wzX2KYXmBcmqZ+Z8uzhJIeyfbANeP2e7vkl+W3HnRRGVklMp/0xDA=
  ciphertext: OYtEew+Emnh/Qnxph1wdRmfwgKTK6VknuBDoXzMuhhgKa4RSvCxfUq0mPCHftMEOBT1RP7VhvVLYS1C0WcN5ZQkOtG3zGaW43hpLtfExOJw=
- key_id: arn:aws:kms:us-east-1:477593580061:key/5abf5adc-e0b7-4df5-bb5e-a42f7b6f4888
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjGKDJeTvC9Smjh5kvaPCZhKrQzkdNH/X2lzLUr9dRntAAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDKy6Jp+0qlOi9phqSAIBEIA78VNuSok9a2e3QxzNm5H5B+UPlhN5edQ1kzAZtapkOf3MBTX7ZmtIZ2Ma/c4E42NYpFf0bCmke+ByfqY=
  ciphertext: Owz78FzmK1rbgAWxbv1ophArcVOaEPkScmVOPCGdbooZLbfNlZukdEw2lUYHZmNlWccFAZAmr9gCUIMrBcR979qFDa294FQSimRwI6grl/A=
local::session-secret:
- key_id: arn:aws:kms:us-west-1:477593580061:key/c9e8618c-1fee-4400-a7d0-0914d433f25e
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjOcf0L8wNJeJByFP9BGFtLH/4xBpSevkIQANEiasdfFwAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDHp5WLfF8hknCH3zGQIBEIA7QGJ8lAZ6wKBlIkco7RVK8O0SuCZycOo+TVAY3mTSsTLeLm4jl0rWjBI/uJ6U5zuuNSxS9Jx5/P+rFL0=
  ciphertext: OPVkd2ujUN+U5FAwifs6zdzkgiEG52pB565SBdkXqUE/YJjElVLD3AlHiOlqNaLRZfQr/g==
- key_id: arn:aws:kms:us-west-2:477593580061:key/e5ebd4c6-e24a-4159-8eee-936148bb73bf
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHj6hSFXIChokq2jG90/VQtkQWJULdzekrDyuaPdAwNk4wAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDHT3FL9r0qIRRGQlOQIBEIA77a8R/gl20/5aL4z7FKoF85SXDTo6aCXVXupMo/tt792rrpNlru6CyRF6ue+AhxxPckdEOIDPTmd8JoU=
  ciphertext: IIWvS9ujEQNtUkIw161/wpkHPqdhVm9MnblOnWKH2OgSl9k7MVNlsRRqplhAJkFl4NJ+Og==
- key_id: arn:aws:kms:us-east-1:477593580061:key/5abf5adc-e0b7-4df5-bb5e-a42f7b6f4888
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjGKDJeTvC9Smjh5kvaPCZhKrQzkdNH/X2lzLUr9dRntAAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDE/kf7Rplczf7bBFZgIBEIA7hRgJps1Amgpt5IDbIbRJi/SiZS7MQr8wG3N4oCq+/X1AVVbRITxSRYyYOC57VqZt9ZeJSO2Ui+NyA/8=
  ciphertext: Hs04gl9F02JjoauO5qez1PPZ7laPaRy+YtytdtCJxg5IRQrQoFI/eBBVkC1oIOc1YX+NGA==
prod::id-me-client-id:
- key_id: arn:aws:kms:us-west-1:477593580061:key/c9e8618c-1fee-4400-a7d0-0914d433f25e
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjOcf0L8wNJeJByFP9BGFtLH/4xBpSevkIQANEiasdfFwAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDNsDvya1xiedh53pOAIBEIA75p60P2JWW2szWGRuhY2g+7zC1lg9Ef7NLfKTBIGZuA2vaYZgl+2xYMj29lSvjo8IyCTovZ1fBDd9/3o=
  ciphertext: 1MuNU5zDkKPhHYZK8g9tKBC5DQ0HmUnqVXHPcsvvyrysW+LI9qhUqexBuzVljRt+2lw77bTuHsqz6J/xUNtpp94BolrQbSiW
- key_id: arn:aws:kms:us-west-2:477593580061:key/e5ebd4c6-e24a-4159-8eee-936148bb73bf
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHj6hSFXIChokq2jG90/VQtkQWJULdzekrDyuaPdAwNk4wAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDH8zLCAiAJnD2UY/ZwIBEIA7odLCoboLQ4RTG6EHgLrgznXPEziJfV4NpfC+P5p0R1/GGY2Wh4rUoX0J86/ScFps4+U7EqwPHdPzC8A=
  ciphertext: a5Nug0/DAuka9k3rzFukbzaUpeFdmmqBBm2l5wTpdSuKL52clVsw9wXLx5BYW7CNd5EsG0Q9AxaTEYZAUoaZ9wSz3Uwg+wym
- key_id: arn:aws:kms:us-east-1:477593580061:key/5abf5adc-e0b7-4df5-bb5e-a42f7b6f4888
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjGKDJeTvC9Smjh5kvaPCZhKrQzkdNH/X2lzLUr9dRntAAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDFdIhS/lSPfB9QyDzwIBEIA7jW60ek90p9pSCgLGyQEL5MBdi1iNn/kCVxp6DQvgaGkwGSPwoAZZGILoNM+yEGqJhI2M7zu7c5kGfG4=
  ciphertext: CwOF4V+1SdaG4u9kPjK95I3fHoxkvW/2oV9XBR44ecBoAVRh+taKbpDmc0tNrVJFvQwqUsiwTh4y5yEEGez4fzJeYvf/SrEZ
prod::id-me-client-secret:
- key_id: arn:aws:kms:us-west-1:477593580061:key/c9e8618c-1fee-4400-a7d0-0914d433f25e
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjOcf0L8wNJeJByFP9BGFtLH/4xBpSevkIQANEiasdfFwAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDCFgIQiMIK4mHJwnPAIBEIA7j/9gB1mAQDv7uQ9JpqDJxY9TwJJT3h3S4gNvjvIcPBOYilM8su1gyk5H5B/9SOJxceymJtUlV+skuXM=
  ciphertext: kfKUWmQd6mAS3QLSB8AzeEGbsFexRl6loee8ZKQyds4v0cbjBTl/Q/hpsphFRuWUJ+WhOhUMHfPnrk0BUIyxtXSWj5JGbEN4
- key_id: arn:aws:kms:us-west-2:477593580061:key/e5ebd4c6-e24a-4159-8eee-936148bb73bf
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHj6hSFXIChokq2jG90/VQtkQWJULdzekrDyuaPdAwNk4wAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJDT/5Y0U+vIlUwe2QIBEIA7kJCedBq9gk1uwA7Y6L/KPs5ReuMjcLnU3KBrY1ocgzIbzmsqunhYM31XI2gWiH5zeYPWp0aBsUSt2oc=
  ciphertext: VJlAOHzoXYGABenE8+p47x/Pb62iOtQKESFTT+ecj6gdCubn9vJb+IPWqQHfRr4WcCj5Q2TnNhtTwfvd/oFS+wf74+L/f7ce
- key_id: arn:aws:kms:us-east-1:477593580061:key/5abf5adc-e0b7-4df5-bb5e-a42f7b6f4888
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjGKDJeTvC9Smjh5kvaPCZhKrQzkdNH/X2lzLUr9dRntAAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDLLP1D8W2w8fqmPvjwIBEIA7UQZzlNQugAGSneEtCtHwsMbL9hkJWGBXUw2rLG19ndDv2PB5RjDUpRjwhlU/wtz+Ea0cFz6NYc23kbQ=
  ciphertext: 7EXg2Qze5o4LaxeEyVEQMLYsgd/BSrDskqt5H8CiyvRxI4UIx6bU7rNU3/vfvqbS0GwwSM/DTFkIdd5N3TchJLJU3r+l8frI
prod::session-secret:
- key_id: arn:aws:kms:us-west-1:477593580061:key/c9e8618c-1fee-4400-a7d0-0914d433f25e
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjOcf0L8wNJeJByFP9BGFtLH/4xBpSevkIQANEiasdfFwAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDHNf8tLo6FgkV/QYWAIBEIA7ELIsP2DyDGV3QOkYdKBZCxIcp7ogztIpFDHmN3Rqqp4TO/xfXzT8uWYyo++3UzDfw42vlzfSxNo0Bc4=
  ciphertext: 6pgJG7NIfL1IKoYEGo2EWAn+GXzo2poraX/w6LlLeKXpAbYibQe++kOXSSPWyJNijdqyNj+TXrRCW0b6898p+G6WG1Wwi+Y3
- key_id: arn:aws:kms:us-west-2:477593580061:key/e5ebd4c6-e24a-4159-8eee-936148bb73bf
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHj6hSFXIChokq2jG90/VQtkQWJULdzekrDyuaPdAwNk4wAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDKqFdOSn/AXOEs7WbwIBEIA7CAvvHW9Syvpe4IPN7uD2i/pR8JI/Ph3gLvs4tl4ETBodt2sFGmr/M/KpLlqTupjxU4iZTEFNKVyALrE=
  ciphertext: CGCzm0CUpsxl7UD835iYNG+HC2NIIoa4mAux9SIQjq+AaWTjhCZD2Kib8PiboykXrepe1VctWhACnnjhmUd40Db9AmND9qwb
- key_id: arn:aws:kms:us-east-1:477593580061:key/5abf5adc-e0b7-4df5-bb5e-a42f7b6f4888
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjGKDJeTvC9Smjh5kvaPCZhKrQzkdNH/X2lzLUr9dRntAAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDMZESclODrNc/EPLegIBEIA7mbjLoDACguYVWhIGaD23LO5NRRL7x4EXZESGYRXdgYUsA2CdjqTxkP2OcY/8oWLErG2WGJHTfFuIw2E=
  ciphertext: oWlJkqkTPDmnJ+bQkMd+PMhlQ7CkknieOv4HpTihwMD6rQVs3xrlftPoCIo6axmHcUICEJygrU+0GIA3eSJVun+cp2h2fvFr
test::id-me-client-id:
- algorithm: none
  ciphertext: dGVzdF9pZF9tZV9jbGllbnRfaWQ=
test::id-me-client-secret:
- algorithm: none
  ciphertext: dGVzdF9pZF9tZV9jbGllbnRfc2VjcmV0
test::lob-api-key:
- key_id: arn:aws:kms:us-west-1:477593580061:key/c9e8618c-1fee-4400-a7d0-0914d433f25e
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjOcf0L8wNJeJByFP9BGFtLH/4xBpSevkIQANEiasdfFwAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDL0rYMFU7b+uQDeWNgIBEIA7JnOaXrE7DuoDqn8cCHcs5bHJIWbUFFA4v7wf+hz+dBCOR9oE9wvN60BzS4PBzn7h5oOJ1qyfSgUc1UE=
  ciphertext: qVlBdoGsS3c13XbDYGF/AhAkktgTAC1bttmV0PAsO/+IIR3+evb36xuawNX9VWf8ZeBlwpZTxkhwVvafX2ZcGs+PEnZumdMJ6lnBdoxQksA=
- key_id: arn:aws:kms:us-west-2:477593580061:key/e5ebd4c6-e24a-4159-8eee-936148bb73bf
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHj6hSFXIChokq2jG90/VQtkQWJULdzekrDyuaPdAwNk4wAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDGnXDpiZ7LnQS9GKeAIBEIA7JxaXqV/76cBiZy+QXemsMFIIGS0AhGmM9jNUQ5K2t0F9n64fUmKY1cRJLFCTORB0sCzXoLXdSd3u/Ho=
  ciphertext: VVb8azdveIldqGo/Azx6cFz+XiubBNm75WG3qdKEnYLj6jDz6wF7rCux/gYHQ7pSxu8N4QiRPqc3Z4f0gHu/NP3tPSR5KG8veRMT00+Dy+M=
- key_id: arn:aws:kms:us-east-1:477593580061:key/5abf5adc-e0b7-4df5-bb5e-a42f7b6f4888
  key_manager: kms
  algorithm: secretbox
  key_ciphertext: AQEBAHjGKDJeTvC9Smjh5kvaPCZhKrQzkdNH/X2lzLUr9dRntAAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDAlvHCbxdFJpykwqgQIBEIA7RATlGNm4xTl3+l6Xp/2qncUXMMHA2RHb67Ey7bNp29ahd3WnWpSgykDnFKWw414RyumAYHILo3Gl0VQ=
  ciphertext: VKrC4q0nsk+kUOCZ+B4TOBAEULKx6uGjFFrcR55oXkoUkQCxiUGnyTgtAd1BqYO712WFG63WbwwH3GNahulnXn+D3hzpDFWV2UXkLztN+Xs=
