_keys:
- algorithm: none
test::id-me-client-id:
- algorithm: none
  ciphertext: c29tZS1jbGllbnQtaWQ=
test::id-me-client-secret:
- algorithm: none
  ciphertext: c29tZS1zZWNyZXQtaWQ=
test::lob-api-key:
- algorithm: none
  ciphertext: dGVzdF9sb2JfYXBpX2tleQ==
test::secret:
- algorithm: none
  ciphertext: c3R1ZmY=
test::session-secret:
- algorithm: none
  ciphertext: c2hoaGhoaGhoaGho
